package com.recruit.model;

public class Company {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.cname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.tel
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.detail
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String detail;
    /**
     * created by teemo 2018Äê9ÔÂ6ÈÕ
     * @param cname
     * @param name
     * @param address
     * @param tel
     * @param detail
     */
    public Company(String cname, String name, String address, String tel, String detail) {
		super();
		this.cname = cname;
		this.name = name;
		this.address = address;
		this.tel = tel;
		this.detail = detail;
    }
	public Company() {
		// TODO Auto-generated constructor stub
		super();
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.cname
     *
     * @return the value of company.cname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.cname
     *
     * @param cname the value for company.cname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.tel
     *
     * @return the value of company.tel
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.tel
     *
     * @param tel the value for company.tel
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.detail
     *
     * @return the value of company.detail
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.detail
     *
     * @param detail the value for company.detail
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }
	@Override
	public String toString() {
		return "Company [cname=" + cname + ", name=" + name + ", address=" + address + ", tel=" + tel + ", detail="
				+ detail + "]";
	}
}