package com.recruit.model;

import java.util.Date;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.newsTime
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private Date newstime;
    /**
     * created by teemo 2018Äê9ÔÂ6ÈÕ
     */
    public News() {
		super();
	}
	public News(Integer id) {
		super();
		this.id = id;
	}
	public News(String title, String content) {
		super();
		this.title = title;
		this.content = content;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.newsTime
     *
     * @return the value of news.newsTime
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public Date getNewstime() {
        return newstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.newsTime
     *
     * @param newstime the value for news.newsTime
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setNewstime(Date newstime) {
        this.newstime = newstime;
    }
	@Override
	public String toString() {
		return "News [id=" + id + ", title=" + title + ", content=" + content + ", newstime=" + newstime + "]";
	}
	public News(String title, String content, Date newstime) {
		super();
		this.title = title;
		this.content = content;
		this.newstime = newstime;
	}
	
}