package com.recruit.model;

import java.util.Date;

public class Recruit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.id
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.cname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.position
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.salsry
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private Integer salsry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.number
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.recruitTime
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private Date recruittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.address
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.degree
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.inf
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String inf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.id
     *
     * @return the value of recruit.id
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.id
     *
     * @param id the value for recruit.id
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.cname
     *
     * @return the value of recruit.cname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.cname
     *
     * @param cname the value for recruit.cname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.position
     *
     * @return the value of recruit.position
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.position
     *
     * @param position the value for recruit.position
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.salsry
     *
     * @return the value of recruit.salsry
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public Integer getSalsry() {
        return salsry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.salsry
     *
     * @param salsry the value for recruit.salsry
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setSalsry(Integer salsry) {
        this.salsry = salsry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.number
     *
     * @return the value of recruit.number
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.number
     *
     * @param number the value for recruit.number
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.recruitTime
     *
     * @return the value of recruit.recruitTime
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public Date getRecruittime() {
        return recruittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.recruitTime
     *
     * @param recruittime the value for recruit.recruitTime
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setRecruittime(Date recruittime) {
        this.recruittime = recruittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.address
     *
     * @return the value of recruit.address
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.address
     *
     * @param address the value for recruit.address
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.degree
     *
     * @return the value of recruit.degree
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.degree
     *
     * @param degree the value for recruit.degree
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.inf
     *
     * @return the value of recruit.inf
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getInf() {
        return inf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.inf
     *
     * @param inf the value for recruit.inf
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setInf(String inf) {
        this.inf = inf;
    }

	@Override
	public String toString() {
		return "Recruit [id=" + id + ", cname=" + cname + ", position=" + position + ", salsry=" + salsry + ", number="
				+ number + ", recruittime=" + recruittime + ", address=" + address + ", degree=" + degree + ", inf="
				+ inf + "]";
	}
}