package com.recruit.model;

public class Request {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.id
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.recruitId
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private Integer recruitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.cname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.sname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    private String sname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.id
     *
     * @return the value of request.id
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.id
     *
     * @param id the value for request.id
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.recruitId
     *
     * @return the value of request.recruitId
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public Integer getRecruitid() {
        return recruitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.recruitId
     *
     * @param recruitid the value for request.recruitId
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setRecruitid(Integer recruitid) {
        this.recruitid = recruitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.cname
     *
     * @return the value of request.cname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.cname
     *
     * @param cname the value for request.cname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.sname
     *
     * @return the value of request.sname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.sname
     *
     * @param sname the value for request.sname
     *
     * @mbggenerated Tue Sep 04 16:15:47 CST 2018
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

	@Override
	public String toString() {
		return "Request [id=" + id + ", recruitid=" + recruitid + ", cname=" + cname + ", sname=" + sname + "]";
	}

	public Request(Integer recruitid, String cname, String sname) {
		super();
		this.recruitid = recruitid;
		this.cname = cname;
		this.sname = sname;
	}

	public Request(Integer id, Integer recruitid, String cname, String sname) {
		super();
		this.id = id;
		this.recruitid = recruitid;
		this.cname = cname;
		this.sname = sname;
	}

	public Request() {
		super();
		// TODO Auto-generated constructor stub
	}
	
}